name: Bug Report 🐛
description: Create a report to help us improve the Baloise Design System
title: '🐛 fix(component): title'
labels: '🐛 Bug'
assignees: ''
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe in detail the issue you're having.
    validations:
      required: true
