name: ✨ Feature Report
description: Create a report to help us improve the Baloise Design System
title: "✨ feat(component): title"
labels: ["✨ Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: textarea
    id: description
    attributes:
      label: Please describe your request in one or two sentences.
      description: A clear and concise description of what the feature does.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Explain the Use Case
      description: Provide a use case for the problem that this feature would address.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe Preferred Solution
      description: Provide a precise and succinct explanation of how you want to add this feature into the Baloise Design System.
  - type: dropdown
    id: breaking-changes
    attributes:
      label: Will this feature introduce breaking changes?
      default: "No"
      options:
        - "No"
        - "Yes"
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be relevant to your issue..
