on:
  issues:
    types: [ assigned ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        with:
          openPR: true
          copyIssueAssigneeToPR: true
          commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}