name: Merge Tester

on:
  workflow_dispatch:
    branches:
      - "main"

jobs:
  release:
    name: Merger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Merge main -> released
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: released
          github_token: ${{ secrets.GITHUB_TOKEN }}
