name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo Changeset output
        run: |
          echo "Changeset published - ${{ steps.changesets.outputs.published }}"
          echo "Changeset publishedPackages - ${{ steps.changesets.outputs.publishedPackages }}"
          echo "Changeset hasChangesets - ${{ steps.changesets.outputs.hasChangesets }}"
          echo "Changeset pullRequestNumber - ${{ steps.changesets.outputs.pullRequestNumber }}"

      - name: Merge main -> released
        if: steps.changesets.outputs.published == 'true'
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: released
          message: "🚀 release: ${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        if: steps.changesets.outputs.published == 'true'
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: 'v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}'
          message: '${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}''
