name: Snapshot Release&Publish

on:
  workflow_dispatch:

jobs:
  release:
    name: Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm build

      - name: Snapshot Release
        run: npm run snapshot:version

      - name: Snapshot Publish
        run: npm run snapshot:publish

      - name: Git Reset
        run: git reset --hard
